# Default values for acme-cluster-issuer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

acme:
    # Email for ACME provider to contact you in case of any problems.
    email: ""

    # Server of ACME provider (default to production Lets Encrypt.)
    server: "https://acme-v02.api.letsencrypt.org/directory"

ingress:
    # Class of ingress provider used for verification.
    # Defaults to traefik, configured with:
    # "--providers.kubernetesIngress.ingressClass=traefik"
    class: traefik
